# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-02-18 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='media/courseorg/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
